linuxmint/cinnamon-control-center

- panels/color/cc-color-panel.c
Fixes
https://bugzilla.redhat.com/show_bug.cgi?id=1119408
```
Description of problem:
1. Open Cinnamon Control Center
2. Select 'Color'
3. Select a device (I picked my printer)
4. Select a color profile (I picked Default RGB)
5. Click 'View details'
crash occurred at this point.
```
based on
https://git.gnome.org/browse/gnome-control-center/commit/panels/color/cc-color-panel.c?h=gnome-3-14&id=e9b0527b4b346e2c4ff2ae00bbf0c415186a5a85
> color: Do not set the 'View Details' button for virtual profiles.

- panels/display/cc-display-panel.c
g_list_nth_data just returns NULL if either list or element is NULL
> cc-display-panel: safer access to list element's data

- panels/network/cc-network-panel.c
Taken from upstream commit
https://git.gnome.org/browse/gnome-control-center/patch/panels/network/cc-network-panel.c?id=f30e6df1d4665b06a45ad7bbe7a2ed2bfa9387f5
> Remove the NetworkManager version checking altogether

- panels/network/connection-editor/ce-page-ip4.c
There are several items missing from the address combo box. These can be set by other means (i.e. Network Connections) so they need to be available here too.
> [network] Add list store items for IPv4 methods

- panels/network/connection-editor/firewall-helpers.c
The call to nm_setting_connection_get_zone() returns a pointer to
memory that will be freed before the D-Bus reply handler is called.
Make sure to take a copy of the string, and free it when finished.
https://bugzilla.gnome.org/show_bug.cgi?id=739971
https://git.gnome.org/browse/gnome-control-center/patch/panels/network/connection-editor?id=dba40e13019c9adef1137a13e3a065c7a048ea46
> network: Allocate storage for zone name during D-Bus call

- configure.ac
This used to be used for the background panel which was removed.
> Remove unused configure options

- panels/network/connection-editor/net-connection-editor.c
Based on https://git.gnome.org/browse/gnome-control-center/commit/panels/network?id=2e6149b4b83cd6ce47ad079a6df717e88a67998a
From 2e6149b4b83cd6ce47ad079a6df717e88a67998a Mon Sep 17 00:00:00 2001
From: Rui Matos tiagomatos@gmail.com
Date: Tue, 26 Jan 2016 18:35:52 +0100
Subject: network: Don't try to get secrets for new connections
We don't need secrets for new connections and, in fact, trying to
retrieve secrets in that case will fail because we have a plain
NMConnection instead of a NMRemoteConnection.
The above mentioned error would result in the page never being
initialized.
> network: Don't try to get secrets for new connections

- configure.ac
- panels/Makefile.am
- panels/network/Makefile.am
- panels/network/cc-network-panel.c
Hi from the Gentoo user!
I've created a set of patches to be able to disable ModemManager while keeping NetworkManager and network panel working and also Colord (patch from Gentoo) during configure / building stages.
Would be great if you could merge and adopt changes for the next release as it gives better control over build deps.
Thanks in advance!
> Optional NetworkManager, ModemManager, Colord

- panels/network/net-device-simple.c
Based on https://git.gnome.org/browse/gnome-control-center/commit/panels/network?id=ca667d9928783423d8ff8f3e8a5dc9ac1626334e
The property might not exist and we would g_free() an uninitialized pointer. Using the proper API avoids all that. 
https://bugzilla.gnome.org/show_bug.cgi?id=783839
Shoud fix the crash in #186
> network: Avoid crashing if the NMDevice doesn't have a hw-address

- panels/color/cc-color-panel.c
- panels/color/color-module.c
- panels/common/cc-common-language.c
- panels/common/cc-language-chooser.c
- panels/common/gdm-languages.c
- panels/common/list-languages.c
- panels/datetime/cc-datetime-panel.c
- panels/datetime/datetime-module.c
- panels/display/cc-display-panel.c
- panels/display/cc-rr-labeler.c
- panels/display/display-module.c
- panels/network/cc-network-panel.c
- panels/network/network-module.c
- panels/online-accounts/cc-online-accounts-panel.c
- panels/online-accounts/online-accounts-module.c
- panels/region/cc-region-panel.c
- panels/region/cinnamon-region-panel-xkb.c
- panels/region/cinnamon-region-panel-xkblt.c
- panels/region/cinnamon-region-panel-xkbltadd.c
- panels/region/cinnamon-region-panel-xkbot.c
- panels/region/region-module.c
- panels/wacom/cc-wacom-page.c
- panels/wacom/cc-wacom-panel.c
- panels/wacom/cc-wacom-stylus-page.c
- panels/wacom/csd-wacom-device.c
- panels/wacom/wacom-module.c
Repeated calls to gtk_builder_set_translation_domain() and inclusions of glib-internal calls can be avoided easily, when the textdomain is setup properly during initialization of the corresponding module.
> all: Simplify and fix i18n

- panels/network/cc-network-panel.c
- shell/cc-panel.c
- shell/cc-shell.c
- shell/cc-shell.h
- shell/cinnamon-control-center.c
- shell/control-center.c
Backports from almost 5 years ago introduced a bug, which causes problems
with some networks as eduroam. You have to manually configure those
networks, because the configuration dialog does not pop up.
This pull request backports the rest from gnome-control-center to fix
this issue. The backported commits are:
* https://gitlab.gnome.org/GNOME/gnome-control-center/commit/9977bb200ea66b2e8ee1d52d0400c4e27bf4b352
* https://gitlab.gnome.org/GNOME/gnome-control-center/commit/4e42a3613341cdbeb7954da53d15de1aa155d0db
Fixes https://github.com/linuxmint/cinnamon/issues/3623 and https://github.com/linuxmint/cinnamon/issues/7837
> Fix network settings, fixes e.g. eduroam

- panels/display/display-capplet.ui
Get rid of a couple dim-labels and usages of italics
This looks like more changes then it actually is because it was saved from a newer Glade version
> display: Clean up a couple labels in ui file

- panels/display/display-capplet.ui
Doing this so we can remove it in the cinnamon settings module. This allows
the monitor display area to completely fiil the frame.
> display-applet.ui: Add some margins

- configure.ac
To my understanding, checks for dependencies I am removing were migrated into `cinnamon-settings-daemon` or made redundant otherwise. There is no any good reason to keep these around as they only confuse people.
Please, let me know if I am missing something, happy to adjust/rework things as needed. Thanks in advance!
> Remove checks for unused dependencies

- configure.ac
- debian/rules
- panels/display/cc-display-panel.c
- panels/display/display-capplet.ui
depends on: linuxmint/cinnamon-desktop#150
Reworks the ui for display settings a bit:
- Re-introduce an 'automatic' user interface scale setting.  This was somewhat removed in the scaling changes - auto worked, but only until you did something to alter the display settings.  The ui will now allow explicitly setting the current configuration to 'automatic' mode.
- Use a switch to control access to fractional scaling.  This switch is disabled if the ui scale is set to 'automatic'.  Toggling the switch enables or disables fractional scaling.  If the switch is toggled off, any fractional scaling values on any monitors in the configuration are reset, and the scale will follow the ui scale setting.  Turning the ui scale to automatic will reset the fractional scale to equal the ui scale, and …
> Display module fixes (scaling)

- panels/network/cc-network-panel.c
Fixes #254 . There is an issue with `-Dnetworkmanager=true -Dmodemmanager=false` giving an undefined reference because the modem header is included and used by the network panel source file.
> Add ifdefs to prevent undefined reference to modem functions in network panel

- panels/network/cc-network-panel.c
- panels/network/net-device.c
And don't destroy the ui before the nm client is disposed of.
Fixes #269
> network panel: Don't try to rebuild the ui during shutdown.

- install-scripts/desktop-file-links.py
- install-scripts/meson.build
Fixes regression in commit 5aa5fab4348de4496efe9ec0b5faa20be234d56e. The created symlinks always considered the directory to be installed to, and created absolute symlinks pointing from the source to the destination. This is wrong, because while the source needs to be installed *into* the directory to be installed to, the destination needs to not include the $DESTDIR.
There are also some sub-optimal design points around scripting the install prefix. Particularly, Meson has a dedicated variable for the combination of DESTDIR + prefix, so use that instead of manually slicing up the prefix so that `os.path.join` won't drop the DESTDIR. The other solution would be to acknowledge that DESTDIR (at least on non-Windows systems) uses string concatenation, not path-joining semantics, but... Meson …
> meson: fix installation of symlinks

- install-scripts/meson.build
In commit ca95ce7dfc4872ecef88b0074d2bee8f097d0394 some symlink creation is handled for all panels, without first checking whether those panels are installed.
Make sure to only try installing those symlinks if their accompanying options/dependencies are enabled/found.
Fixes #289
> meson: fix regression in installing with some panels disabled

- debian/control
- debian/copyright
d/control:
- remove libdbus-1-dev build-dep, not needed anymore
- remove Provides cinnamon-capplets-data, not needed anymore
> small debian packaging improve

- meson.build
- shell/meson.build
The Nix package manager used by NixOS (and available on all unix systems), uses a sandboxed environment where it is not possible to have global building dependencies. Without this change the build with fails with:
```
[15/124] Compiling C object shell/cinnamon-control-center.p/cinnamon-control-center.c.o
FAILED: shell/cinnamon-control-center.p/cinnamon-control-center.c.o 
gcc -Ishell/cinnamon-control-center.p -Ishell -I../shell -I. -I.. -I/nix/store/qbvaw0nl5rvmwm6ljsmvq7ciazqvcd2j-gtk+3-3.24.34-dev/include/gtk-3.0 -I/nix/store/mkn4f22mpfk654j46r5644fvg73cxz82-atk-2.38.0-dev/include/atk-1.0 -I/nix/store/0a9b4bv93s2b94q0fa2h4r0m55qy92fx-glib-2.72.3-dev/include -I/nix/store/0a9b4bv93s2b94q0fa2h4r0m55qy92fx-glib-2.72.3-dev/include/glib-2.0 …
```
> build: add missing gio-unix-2.0 dependency

- panels/region/cinnamon-region-panel-xkb.c
- panels/region/cinnamon-region-panel-xkb.h
While working myself through #288, libgnomekbd got updated to v3.28 and removed some `extern` declarations from their public headers.
I decided to redefine them in `cinnamon-region-panel-xkb.c` instead of just adding `extern` declarations to avoid another patch if the definitions in libgnomekbd are changed to `static`.
> region panel: add keys removed from libgnomekbd's API in v3.28

- panels/display/cc-display-arrangement.c
If a monitor has no preferred mode, for example due to an issue in
muffin, get_scaled_geometry did segfault when the monitor is inactive.
It was inactive because the chosen configuration wasn't shown as active
mode either.
This resulted in not being able to open the display panel to even change
to a working configuration without compiling cinnamon-control-center
myself.
With this patch, the panel does open even without preferred mode on a
monitor.
Closes #288
> display panel: fallback if no preferred mode is set

- panels/network/connection-editor/net-connection-editor.c
Based on https://github.com/GNOME/gnome-control-center/commit/167d11e2107e46b4621cf6fc370c5b191b4b7732
> network: Fix warning about missing cast to GtkWidget*

- panels/network/network-dialogs.c
Remove unnecessary serial config and allow IPv4+IPv6 per default
> network: better default settings for cellular connections

- panels/network/network-dialogs.c
As GTK is loaded first, while libNMA is loaded later with the network panel extension, the GtkBuilder for the wizard GUI doesn't know the libNMA types.
To fix that, we need to ensure the registration of these types.
Fixes: #225, fixes #246
> network: fix crash when adding cellular connection

- meson.build
These warnings don't trigger. They've stuck around across build systems somehow.
> meson: remove CFLAGS that were carried over from decades ago and aren't needed

- panels/network/wireless-security/utils.c
musl libc has its own `ethhdr` struct that is always defined in <netinet/ether.h>. Normally, "nm-default.h" prevents the redefinition of `ethhdr` if that struct is already defined, but because "nm-default.h" comes before <netinet/ether.h>, it will define the struct, causing a redefinition error.
The patch for this comes from Void Linux, and I am a Chimera Linux packager.
> network: prevent redefinition error when building with musl libc

- panels/network/connection-editor/ce-page-vpn.c
Produces warning using the same format as nm-connection-editor when a VPN connection editor plugin cannot be loaded.
> network: Could not load editor VPN plugin warning
